#!/usr/bin/env php
<?php

set_time_limit(0);

require_once(__DIR__ . '/../vendor/autoload.php');

use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;

use Dbu\GhCollector\Command\FetchDataCommand;

$parameters = Yaml::parse(__DIR__ . '/config/parameters.yml');
$console = new Application();
$console->add(new FetchDataCommand($parameters['github.username'], $parameters['github.password'], $parameters['repositories']));
$console->run();
